-- MySQL Script generated by MySQL Workbench
-- Wed Aug  1 20:01:29 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Cidade`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cidade` (
  `COD_CIDADE` INT NOT NULL,
  `NOME_CIDADE` VARCHAR(50) NOT NULL,
  `COD_UF` CHAR(2) NOT NULL,
  PRIMARY KEY (`COD_CIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Cliente` (
  `COD_CLIENTE` INT NOT NULL AUTO_INCREMENT,
  `NOME_CLIENTE` VARCHAR(100) NOT NULL,
  `dataNascimento` VARCHAR(10) NOT NULL,
  `CPF` CHAR(11) NOT NULL,
  `TEL_1` VARCHAR(11) NOT NULL,
  `TEL_2` VARCHAR(11) NULL,
  `ENDERECO_ENTREGA` VARCHAR(200) NOT NULL,
  `NUMERO_END` VARCHAR(6) NOT NULL,
  `CEP` CHAR(8) NOT NULL,
  `Cidade_COD_CIDADE` INT NOT NULL,
  PRIMARY KEY (`COD_CLIENTE`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC),
  INDEX `fk_Cliente_Cidade_idx` (`Cidade_COD_CIDADE` ASC),
  CONSTRAINT `fk_Cliente_Cidade`
    FOREIGN KEY (`Cidade_COD_CIDADE`)
    REFERENCES `mydb`.`Cidade` (`COD_CIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Venda`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Venda` (
  `COD_VENDA` INT NOT NULL,
  `DATA_VENDA` DATE NOT NULL,
  `VALOR_VENDA` DECIMAL NULL,
  `Cliente_COD_CLIENTE` INT NOT NULL,
  PRIMARY KEY (`COD_VENDA`),
  INDEX `fk_Venda_Cliente1_idx` (`Cliente_COD_CLIENTE` ASC),
  CONSTRAINT `fk_Venda_Cliente1`
    FOREIGN KEY (`Cliente_COD_CLIENTE`)
    REFERENCES `mydb`.`Cliente` (`COD_CLIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Parcela`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Parcela` (
  `COD_PARCELA` INT NOT NULL AUTO_INCREMENT,
  `DATA_VENC` DATE NOT NULL,
  `VALOR_PARCELA` DECIMAL NOT NULL,
  `DATA_PGTO` DATE NOT NULL,
  `VALOR_PAGO` INT NOT NULL,
  `Venda_COD_VENDA` INT NOT NULL,
  PRIMARY KEY (`COD_PARCELA`),
  INDEX `fk_Parcela_Venda1_idx` (`Venda_COD_VENDA` ASC),
  CONSTRAINT `fk_Parcela_Venda1`
    FOREIGN KEY (`Venda_COD_VENDA`)
    REFERENCES `mydb`.`Venda` (`COD_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Categoria`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Categoria` (
  `COD_CATEGORIA` INT NOT NULL AUTO_INCREMENT,
  `NOME` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`COD_CATEGORIA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Produto` (
  `COD_PRODUTO` INT NOT NULL,
  `NOME_PRODUTO` VARCHAR(50) NOT NULL,
  `PRECO` DECIMAL NOT NULL,
  `DESCONTO` DECIMAL NOT NULL,
  `DESCRICAO` VARCHAR(300) NULL,
  `QTDE_ESTOQUE` SMALLINT(5) NOT NULL,
  `Categoria_COD_CATEGORIA` INT NOT NULL,
  PRIMARY KEY (`COD_PRODUTO`),
  UNIQUE INDEX `NOME_PRODUTO_UNIQUE` (`NOME_PRODUTO` ASC),
  INDEX `fk_Produto_Categoria1_idx` (`Categoria_COD_CATEGORIA` ASC),
  CONSTRAINT `fk_Produto_Categoria1`
    FOREIGN KEY (`Categoria_COD_CATEGORIA`)
    REFERENCES `mydb`.`Categoria` (`COD_CATEGORIA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Qtd_Vendida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Qtd_Vendida` (
  `Venda_COD_VENDA` INT NOT NULL,
  `Produto_COD_PRODUTO` INT NOT NULL,
  `QTD_VENDIDA` SMALLINT(3) NOT NULL,
  INDEX `fk_Qtd_Vendida_Venda1_idx` (`Venda_COD_VENDA` ASC),
  INDEX `fk_Qtd_Vendida_Produto1_idx` (`Produto_COD_PRODUTO` ASC),
  CONSTRAINT `fk_Qtd_Vendida_Venda1`
    FOREIGN KEY (`Venda_COD_VENDA`)
    REFERENCES `mydb`.`Venda` (`COD_VENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Qtd_Vendida_Produto1`
    FOREIGN KEY (`Produto_COD_PRODUTO`)
    REFERENCES `mydb`.`Produto` (`COD_PRODUTO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
